### ISSUE TITLE
Chaddi should remember everyone's birthday

### ISSUE THREAD

**Issue by vcidst** [arkits/chaddi-tg#10]
Some way to add birthdays

**Comment by bolttacle** [comment]
roses are red
violets are blue 
your mom is gay
so are you

**Comment by ark893** [comment]
no U

**Comment by bolttacle** [comment]
stfu bitch raps like god

**Comment by bolttacle** [comment]
theri maa ka louda saale bhosad ki oulat

**Comment by NitinChandak** [comment]
i want to work on this . So can please elaborate?

**Comment by arkits** [comment]
Thanks for pitching in @NitinChandak ! This is a slightly complicated feature, but here are a few pointers -

- Begin with adding a new birthday element to the Bakchod class in the `src/bakchod_util.py`. 
- Then add a handler for accepting birthday for a Bakchod. Refer to `src/handlers/quotes.py`.
- Finally we will need some kind of scheduled job mechanism. [There was something like implemented long time ago in ChaddiBot](https://github.com/arkits/chaddi-tg/tree/d0b4d7bfdbeafacac1555fde32008548073e8499).  See the references to `job_spam`. The idea would be that you have a job scheduled at 10am everyday, where in you go through each Bakchod, check if it's their birthday, and then post a message.

Feel free to ping us if you get stuck!
