### ISSUE TITLE
Migration to a better DB

### ISSUE THREAD

**Issue by arkits** [arkits/chaddi-tg#19]
Have to investigate better DB options. Thinking about redis, sqlite or Mongo. The data models are not mature enough so have to choose a DB which would support scaffolding-ish.

**Comment by vcidst** [comment]
I've never worked on redis so let's go with that one, would be fun

**Comment by leif-erikson** [comment]
Just move to sqlite. Traffic is very low, concurrent writes won't be an issue. Redis is an overkill for this.
