### ISSUE TITLE
Use a different TTS API that supports Hindi voice

### ISSUE THREAD

**Issue by vcidst** [arkits/chaddi-tg#6]
[SoundOfText](https://soundoftext.com/docs#reference) API seems to support different voices as well and uses the same Google TTS Engine.

If we start using that we can get rid of the gTTS dependency and switch entirely to this API. However they do have a 200 character limit. Will that be enough?

**Comment by arkits** [comment]
gTTS itself has the ability to change the language...

`
from gtts import gTTS
tts = gTTS('Namaskar Mandali', lang='hi')
tts.save('hello.mp3')
`

How would the implementation be? 
We can set the default to Hindi TTS, but then all the English words get spoken incorrectly?

**Comment by vcidst** [comment]
> We can set the default to Hindi TTS, but then all the English words get spoken incorrectly?

Sounds like a feature for a ghati bot

**Comment by vcidst** [comment]
Let's just keep two different commands with both the voices
